ARDUINO_DIR = /usr/share/arduino
ARDMK_DIR = ~/Documents/Arduino-Makefile
# Boards list: https://gist.github.com/wsh32/19d37709bfb5bea4915e810f03b4f26c
BOARD_TAG = uno
USER_LIB_PATH += ./lib/
ARDUINO_LIBS = Wire Servo Adafruit_Motor_Shield_V2_Library
include $(ARDMK_DIR)/Arduino.mk
